// Code generated by protoc-gen-go.
// source: message2.proto
// DO NOT EDIT!

/*
Package message2 is a generated protocol buffer package.

It is generated from these files:
	message2.proto

It has these top-level messages:
	MsgItem
*/
package message2

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MsgItem struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	R                *int32 `protobuf:"varint,2,req,name=r" json:"r,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgItem) Reset()         { *m = MsgItem{} }
func (m *MsgItem) String() string { return proto.CompactTextString(m) }
func (*MsgItem) ProtoMessage()    {}

func (m *MsgItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *MsgItem) GetR() int32 {
	if m != nil && m.R != nil {
		return *m.R
	}
	return 0
}

func init() {
}
